name: Build and deploy container app to Azure Web App - # cmdregistry
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  REGISTRY: dregistrycm.azurecr.io
  IMAGE_NAME: dregistrycm.azurecr.io/mvcimage
  IMAGE_TAG: 1.0${{ github.run_number }}
  AZURE_WEB_APP_NAME: 'cmdregistry'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - name: checkout repository
      uses: actions/checkout@master
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v1
    - name: login into ACR
      uses: docker/login-action@v1
      with:
        registry: https://dregistrycm.azurecr.io/
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: build and push image to ACR
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
    - name: deploy to azure web app
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cmderegistry'
        publish-profile: ${{ secrets:AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ secrets.ACR_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'